### ISSUE TITLE
qt5 pyqt5

### ISSUE THREAD

**Issue by aydemir** [PisiLinuxNew/pisido#1]
@hrngultekin pisido yu pyqt5 e port edebilirmisin
http://www.oqapy.eu/releases/pyqt4topyqt5.tar.gz

**Comment by hrngultekin** [comment]
PisiDo cpp ile yazılmıştır.  Qt5 e port etmeye çalışacağım.
26 Ağu 2015 15:21 tarihinde "yusuf" notifications@github.com yazdı:

**Comment by hrngultekin** [comment]
PisiDo yu qt5 e port ettim fakat qscintilla2 paketini qt5 için derlerken   pyqt5 (python-qt5 ve python3-qt5) paketlerinde sorun ile karşılaştım.python da import etmeye çalıştığımda hata veriyor.
Bu paketlerin yeniden derlenmesi lazim. 
qscintilla2 paketini python paketleri olmadan qt5 için yeniden derledim bu sefer eski paketteki libqscintilla2.so dosyasiyla çakışti. Bu bir problem olur mu bilmiyorum.  Ama sonuç olarak qscintilla2 yi yükledim ve PisiDo qt5 ile sorunsuz çalıştı. Biraz uzun oldu ama paketteki sıkıntıyi anlatmak istedim. Kusura bakmayın.

**Comment by ertugerata** [comment]
paket hatası kısmını anlayamadım. nelerin derlenmesi gerekiyor? hangi Pisi ? 1.2 mi 2.0 mı?

**Comment by hrngultekin** [comment]
Pisi 1.2 de Pyton(3)-qt5 paketi kurulu fakat 'from PyQt5 import QtCore'
şeklinde import etmeye çalışınca hata veriyor ayrıca pyuic5 programini
çalıştırınca da aynı hatayı veriyor.

Hata: Sip modulu api v9.x var pyqt5.qtcore icin api v 11.1 gerekli
31 Ağu 2015 22:54 tarihinde "Ertuğrul Erata" notifications@github.com
yazdı:

**Comment by hrngultekin** [comment]
qt5 e port edildi
