### ISSUE TITLE
Docker imajı ile çalışma

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#2]
@hrngultekin pisido nun bir docker imajı ile çalışması sağlanabilir mi? İlgili docker imajını adresten alacak ve kendisine verilen inşa dosyasını kullanarak o imaj içinde pisi paketini derleyecek.

Eğer böyle bir şey yapılabilirse süper olur.

**Comment by hrngultekin** [comment]
Öncelikle bilmediğim için bağışlayın docker imajı nedir, mantığı nedir?  Biraz açıklar mısınız? 
Açıklamaya göre ne kadar yapabileceğimi söylerim. 

Bu arada biliyorsunuzdur ama yine hatırlatayım pisido kendi terminalinde pisi bi komutuyla derleme işlemini gerçekleştiriyor.

**Comment by hrngultekin** [comment]
Telefondan yazıyorum yazım hataları için özür dilerim.

**Comment by ayhanyalcinsoy** [comment]
Öncelikle yazım hataları çok sorun değil, hepimiz aynı hataları yapıyoruz. 
Docker imajı dediğimiz şey izole bir ortam oluşturuyor ve sadece paketin ihtiyaç duyduğu inşa bağımlılıkları ile paket derliyor. Yine pisi bi kullanıyoruz fark olarak sona --ignore-safety ekliyoruz. Bu şekilde hatalı linklemeler engellenmis oluyor. İsterseniz slacka davet edeyim sizi docker imajını oluşturan ertuğrul abi ile konuşursunuz ve size tam mantığını anlatır.

**Comment by hrngultekin** [comment]
Evet . Nasıl kullanılır öğrenirsem daha iyi yardımcı olurum. Fakat şu an bilgisayar başında değilim.  Bu yüzden çabuk cevap veremeyebilirim.
