### ISSUE TITLE
harici dizin bağlama

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#3]
docker pull ertugerata/pisi-chroot-farm && docker run -v /home/PisiLinux/Masaüstü/PisiLinux_2.0:/git -v /home/PisiLinux/Masaüstü/Pisi2.0/build:/root -v /var/cache/pisi/archives:/var/cache/pisi/archives -v /var/cache/pisi/packages:/var/cache/pisi/packages -itd ertugerata/pisi-chroot-farm bash

yukarıda build, archives ve packages dizinlerinin dockera bağlanması önemli. Bunlar önemli eğer özellikle build dizinini bu şekilde bağlamazsak docker içinde derlenen pisi paketini alıp kullanamayız docker içinde kalır.

**Comment by hrngultekin** [comment]
çalışma alanı seçim kısmına eklendi
