### ISSUE TITLE
her açılışta pisido docker imajı güncellemesin

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#4]
Run butonuna bastığımızda docker imajı kontrolü yapıyor pisido. Onu biz update butonu ile yapalım. Kendi kontrol etmesin. Docker açılışını geciktiriyor.

**Comment by hrngultekin** [comment]
artık  run butonuna tıklandığında güncelleme yapmayak şekilde ayarladım
