### ISSUE TITLE
aynı konteynerı kullanma

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#5]
Mümkünse aynı konteyner ı kullanalım. Kullanılan konteyner dışındaki konteynerları sudo docker ps -a komutu ile listeleyip kullanmadıklarımızı silebilelim.
bazen işler yarım kalıyor. eğer her açılışta son konteyner ı kullanırsak en baştan almak gerekebilir
Sadece docker imajı yenilendiğinde yeni bir konteyner kullanalım.

**Comment by hrngultekin** [comment]
aynı konteynerler artık kullanılabilir
