### ISSUE TITLE
no matching signal for on_btn_..

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#6]
Konsoldan pisido komutu verince aşağıdaki hatayı veriyor ve kalıyor. açılmıyor.

QMetaObject::connectSlotsByName: No matching signal for on_btn_package_clicked(QString)
QMetaObject::connectSlotsByName: No matching signal for on_btn_remove_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_action_Open_Log_triggered()

**Comment by hrngultekin** [comment]
sorun giderildi
