### ISSUE TITLE
konteyner a girmiyor

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/pisido#7]
cuma günü sorun yoktu ancak şuanda konteynera girmiyor. konsoldan pisido çalıştırdığımda konteyner listesi boş görünüyor

**Comment by hrngultekin** [comment]
bu docker ile alakalı galiba bende de oldu 
konsola "sudo docker ps" komutunu girdim  boş görünüyordu

**Comment by ayhanyalcinsoy** [comment]
şimidilik tamam
